
GlobalPresentationSettings:

  StartingText: Press any key to start the presentation
  StartingTextTopPadding: 18

  SelectedSlideTitleColor: Green

  MasterLayoutRatios:
    Navigation: 1
    SlideList: 10
    SlideProgress: 2
    Content: 4

  SlideProgress:
    Width: 100
    LabelText: "[green]Slide Progress[/]"
    LabelJustification: Left
    BarColor: Green

Slides:
  - Title: DON'T SKIP ARM DAY
    Content:
      - !FigletBlock
        Justification: Center
        Color: Green
        Padding:
          Horizontal: 16
          Vertical: 7
        LayoutRatio: 3
      - !MarkupBlock
        Justification: Center
        Padding:
          Horizontal: 16
          Vertical: 1
        LayoutRatio: 1
        Content: "Your [bold slowblink]Bicep[/] Will Thank You!"
      - !MarkupBlock
        Justification: Right
        Padding:
          Horizontal: 16
          Vertical: 1
        LayoutRatio: 2
        Content: |
          Kevin Cefalu
          DevOps Engineer III, Netchex
          kevin.cefalu@outlook.com
          Github: kevinCefalu
          Discord: PsiBit#5498

  - Title: ARM vs Bicep
    Content:
      - !FigletBlock
        Justification: Center
        Color: Green
        Padding:
          Horizontal: 16
          Vertical: 8
        LayoutRatio: 1

  - Title: Demo Time!
    Content:
      - !FigletBlock
        Justification: Center
        Color: Green
        Padding:
          Horizontal: 16
          Vertical: 8
        LayoutRatio: 1
